# Generated by Django 4.2.2 on 2023-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_title_alter_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='static/friendimage')),
            ],
        ),
    ]
