# Generated by Django 4.2.2 on 2023-09-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
